const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const assert = require("node:assert/strict");
const {fromCAD, footprints, simulate} = require("../page/watering-model.js");

const root = path.resolve(__dirname, "../..");
const read = name => fs.readFileSync(path.join(root, name), "utf8");
const model = JSON.parse(read("software/page/model.json"));
const mapping = JSON.parse(read("software/page/controller-map.json"));
const layout = fromCAD(model, mapping), masks = footprints(layout);
const selected = [...new Set([
  ...masks.get(layout.flaps[0].id), ...masks.get(layout.flaps.at(-1).id)
])].sort((a, b) => a - b);
const defaults = {selected, rain_mm: 10, soil_mm: 20, target_mm: 25, capacity_mm: 60, spill_allowed: false};
const specifications = [
  ["Two footprints", {}],
  ["Insufficient rain", {rain_mm: 2}],
  ["No rain", {rain_mm: 0}],
  ["Already satisfied", {soil_mm: 25}],
  ["Empty selection", {selected: []}],
  ["Single cell, protected", {selected: [selected[0]]}],
  ["Single cell, spill allowed", {selected: [selected[0]], spill_allowed: true}],
  ["Whole rectangle", {selected: Array.from({length: layout.cols * layout.rows}, (_, i) => i)}],
];
const near = (a, b) => assert.ok(Math.abs(a - b) < 1e-9, `${a} != ${b}`);
const examples = specifications.map(([name, patch]) => {
  const input = {...defaults, ...patch}, result = simulate(layout, input);
  assert.deepEqual(result, simulate(layout, input));
  near(result.rain_litres, result.admitted_litres + result.excluded_litres);
  near(result.admitted_litres, result.selected_litres + result.outside_litres);
  near(result.initial_soil_litres + result.admitted_litres, result.final_soil_litres + result.overflow_litres);
  assert.deepEqual(result.final_open_flaps, []);
  const requested = result.cells.filter(c => c.selected);
  return {name, input, result, met: requested.filter(c => c.reason === "target_met").length};
});
const golden = examples[0], r = golden.result;
assert.equal(golden.met, selected.length);
assert.ok(selected.length > 0);
near(r.outside_litres, 0);
const ml = litres => (litres * 1000).toFixed(1);
const sources = Object.fromEntries(["software/page/model.json", "software/page/controller-map.json",
  "software/page/watering-model.js"].map(name => [
  name, crypto.createHash("sha256").update(read(name).replace(/\r\n/g, "\n")).digest("hex")
]));
const rows = examples.map(e => `| ${e.name} | ${e.met}/${e.input.selected.length} | ${ml(e.result.selected_litres)} | ${ml(e.result.outside_litres)} | ${ml(e.result.overflow_litres)} |`).join("\n");
const markdown = `# Reproducible watering figures

Generated by \`node software/tools/build_watering_examples.cjs\`; do not edit by hand.
All quantities are simulated at the supplied CAD scale. Defaults: rain 10 mm, soil 20 mm, target 25 mm, capacity 60 mm, outside watering disabled.
The preset uses the first and last mapped footprints, exactly as the page does.

| Scenario | Selected targets met | Selected mL | Outside mL | Overflow mL |
|---|---:|---:|---:|---:|
${rows}

## Default example accounting

- ${selected.length} selected cells, ${r.phases.length} opening phase, ${r.phases.flatMap(p => p.open_flaps).join(" + ")}.
- Event over map: ${ml(r.rain_litres)} mL = ${ml(r.admitted_litres)} admitted + ${ml(r.excluded_litres)} excluded.
- Selected delivery ${ml(r.selected_litres)} mL + outside ${ml(r.outside_litres)} mL = admitted ${ml(r.admitted_litres)} mL.
- Initial soil ${ml(r.initial_soil_litres)} mL + admitted ${ml(r.admitted_litres)} mL = final soil ${ml(r.final_soil_litres)} mL + overflow ${ml(r.overflow_litres)} mL.
- ${r.unused_rain_mm} mm of rain remains after the last opening; all flaps end closed.

These displayed values round independently. Full precision, inputs, phase sequences, all cell results and source hashes (UTF-8, normalized LF) are in [examples.json](examples.json).
Excluded rain includes unselected map area and time with flaps closed; it is not a claim of water saved against a physical baseline.
The whole rectangle contains ${examples.at(-1).result.cells.filter(c => c.reason === "uncovered").length} uncovered cells.

## Geometry and model boundary

${layout.flaps.length} mapped flaps; ${layout.cols} × ${layout.rows} cells; ${(layout.width_m * 1000).toFixed(1)} × ${(layout.length_m * 1000).toFixed(1)} mm bounding rectangle.
Independent 25 mm-radius circular apertures; cell-centre rasterization; overlapping open masks form a union.
Cross-layer/base occlusion, wind, runoff, evaporation, crop response, physical folding and actuators are excluded.
Strict protection can deny geometrically reachable selected cells. The greedy selection is deterministic, not proven globally optimal.
`;
const slides = [
  ["01 / The grower", "Rain is coming.<br>Only two areas need it.", "<p>Imagine a shade-house grower near Apopka, Florida.</p><p>Choose the soil that should receive rain, and protect the neighbouring areas.</p><small>Illustrative scenario · No customer interview or measured crop result claimed</small>"],
  ["02 / The demo", "Choose areas.<br>Apply rain.<br>Watch the roof.", "<ol><li>Select two footprints</li><li>Simulate the 10 mm event</li><li>Inspect targets met and outside delivery</li></ol><p>Switch to the live page for the 45-second demonstration.</p>"],
  ["03 / The decision", "Every opening has<br>a footprint.", "<p>Individual flap combinations → union of circular footprints → soil targets → replan and close.</p><p>Strict protection can refuse an opening that would wet a neighbour. Spill requires an explicit choice.</p><small>Deterministic controller · Browser JavaScript + WebGL team CAD · No runtime AI</small>"],
  ["04 / Reproducible result", `${golden.met}/${selected.length}<br>selected targets met`, `<div class="metrics"><p><strong>${ml(r.selected_litres)} mL</strong> selected delivery</p><p><strong>${ml(r.outside_litres)} mL</strong> outside delivery</p><p><strong>${ml(r.overflow_litres)} mL</strong> overflow</p></div><p>Rain 10 mm · Soil 20 → 25 mm · ${r.unused_rain_mm} mm remaining after the last opening.</p><small>Simulated at the small CAD scale. No yield or water-saving comparison.</small>`],
  ["05 / What is proven", "Software today.<br>Physical validation next.", "<p>Team CAD: 22 flap instances, two overlapping layers and a base.</p><p>Assumed: independent circular rain apertures. Not simulated: cross-layer/base blockage or actual folding mechanics.</p><p>The model accounts for water; the prototype still needs a measured footprint experiment.</p>"],
  ["06 / The ask", "Help us compare<br>choice with delivery.", '<ol><li>Measure actual rain footprints and occlusion</li><li>Validate the selection workflow with one grower</li><li>Connect a small actuator and sensor experiment</li></ol><a href="https://github.com/andomo3/flecto-stop">github.com/andomo3/flecto-stop</a><small>HackMIT 2026 · Abba / Ameya / Shannon · Mechanism inspiration: ITKE Flectofin EP2320015</small>'],
];
const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shade house — farmer-selected watering</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#11281d;color:#f5f4e9;font:clamp(18px,2.1vw,28px)/1.5 system-ui,sans-serif}
section{min-height:100vh;padding:7vh 8vw;border-bottom:1px solid #648673;display:flex;flex-direction:column;justify-content:center;gap:2vh}
.kicker{color:#abcdb4;text-transform:uppercase;letter-spacing:.1em;font-size:.6em}
h1{font-size:clamp(38px,6vw,90px);line-height:1.03;letter-spacing:-.035em;margin:0 0 2vh;max-width:18ch}
p{max-width:60ch;margin:.5em 0}small{display:block;color:#c0d1c3;font-size:.58em;margin-top:3vh}
a{color:#cbecbe}.metrics{display:flex;flex-wrap:wrap;gap:4vw}.metrics p{font-size:.75em}.metrics strong{display:block;font-size:1.7em}
li{margin:.5em 0}@media print{@page{size:landscape;margin:0}section{height:100vh;break-after:page}body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style></head><body>
${slides.map(([label, title, body]) => `<section aria-label="${label}"><div class="kicker">Shade house / ${label}</div><h1>${title}</h1>${body}</section>`).join("\n")}
</body></html>
`;
const outputs = {
  "pitch/examples.json": JSON.stringify({schema: "shadehouse-pitch-examples-1", sources, assumptions: mapping.assumptions, layout, examples}) + "\n",
  "pitch/results.md": markdown,
  "pitch/presentation.html": html,
};
for (const [name, content] of Object.entries(outputs)) {
  if (process.argv.includes("--check")) assert.equal(read(name).replace(/\r\n/g, "\n"), content, `${name} is stale`);
  else fs.writeFileSync(path.join(root, name), content);
}
console.log(`Verified ${examples.length} deterministic scenarios; ${golden.met}/${selected.length} targets, ${ml(r.selected_litres)} mL selected.`);
